### PR TITLE
Add pyproject.toml for Custom Node Registry

### PR DESCRIPTION
**Pull request by haohaocreates**
Hey! My name is HaoHao and I'm from [comfy-org](https://comfy.org/)! We would love to have you join the Comfy Registry, a public collection of custom nodes which lets authors publish nodes by version and automate testing against existing workflows. 

Eventually, the registry will be integrated as a backend for the UI-manager where all nodes will go through a security scan. Nodes that pass these checks will have a verification flag (✅) beside their name on the UI-manager. Feel free to read up more on the registry [here](https://docs.comfy.org/registry/overview#introduction)

Action Required:

- [x] Go to the [registry](https://registry.comfy.org). Login and create a publisher id (everything after the `@` sign on your registry profile). 
- [x] Add the publisher id into the pyproject.toml file.
- [x] Merge the separate Github Actions PR, then merge this PR.

If you want to publish the node manually, [install the cli](https://docs.comfy.org/comfy-cli/getting-started#install-cli) by running `pip install comfy-cli`, then run `comfy node publish`

Otherwise, if you have any questions, please message me on discord at haohao_81202 or join our [server](https://discord.com/invite/comfyorg)!

### CODE REVIEW

**Comment by al-swaiti** [comment]
hi i did this before using comfy cli ,, unfortunately "license = { file = "LICENSE" } not work and give me this error 
image
So i changed it to license = "LICENSE" and thats worked , why this happened 
"

**Comment by haohaocreates** [comment]
Hey! Could you try running on the latest version of Comfy CLI and see if
the object format still gives you that error message?

**Comment by al-swaiti** [comment]
image

**Comment by al-swaiti** [comment]
again when i use old way ,,,, license = "LICENSE"   work

**Comment by al-swaiti** [comment]
further more any chance to work with comfyui ,,, i'm working  alone

**Comment by haohaocreates** [comment]
hey if you update the comfy-CLI to the newest version and try to re-publish
the new object format should work now

**Comment by al-swaiti** [comment]
comfy node publish
warn: The recent workspace None is not a valid ComfyUI path.
Validating node configuration...
Please enter your API Key (can be created on https://registry.comfy.org): 
Publishing node version...
 'name': 'All-IN-ONE-style', 'license': '{"file": "LICENSE"}', 'repository': 'https://github.com/al-swaiti/All-IN-ONE-style'}, 'node_version': {'version': '1.0.1', 'dependencies': []}}
Creating zip file...
No .gitignore file found in /home/abdallah/Desktop/webui/onediff/onediff_diffusers_extensions/examples/davinci/All-IN-ONE-style, proceeding without it.
Uploading zip file...
Upload successful.

**Comment by al-swaiti** [comment]
but i have to changed version ,,, is there option to force push as GitHub

**Comment by al-swaiti** [comment]
mmm do you have any idea about  add T5 clip to be used with  sdxl !

**Comment by haohaocreates** [comment]
Hey feel free to ask your most recent question in our discord, lmk if you
have other questions publishing to the registry!

**Pull request merged**
